export const PostUser = [
  {
    id: 1,
    name: "pratik poudel",
    image: "https://i.pravatar.cc/150?img=33", 
    occupation: "Web Designer",
    education: "B.Sc. CSIT",
  },
  {
    id: 2,
    name: "Joyti magar",
    image: "https://i.pravatar.cc/150?img=47",
    occupation: "UI/UX Designer",
    education: "BBA",
  },
  {
    id: 3,
    name: "Aayush Karki",
    image: "https://i.pravatar.cc/150?img=32", 
    occupation: "Backend Developer",
    education: "B.Sc. CSIT",
  },
  {
    id: 4,
    name: "Sita Sharma",
    image: "https://i.pravatar.cc/150?img=48", 
    occupation: "Graphic Designer",
    education: "BFA",
  },
  {
    id: 5,
    name: "Prakash Rai",
    image: "https://i.pravatar.cc/150?img=36",
    occupation: "Frontend Developer",
    education: "B.Sc. CSIT",
  },
  {
    id: 6,
    name: "Kritika Gurung",
    image: "https://i.pravatar.cc/150?img=50", 
    occupation: "Software Engineer",
    education: "B.E. Software",
  },
  {
    id: 7,
    name: "Bibek KC",
    image: "https://i.pravatar.cc/150?img=38", 
    occupation: "Mobile App Developer",
    education: "B.Sc. CSIT",
  },
  {
    id: 8,
    name: "Asmita Bhandari",
    image: "https://i.pravatar.cc/150?img=52", 
    occupation: "Data Analyst",
    education: "BCA",
  },
  {
    id: 9,
    name: "Roshan Shrestha",
    image: "https://i.pravatar.cc/150?img=40", 
    occupation: "Cloud Engineer",
    education: "B.E. Computer",
  },
  {
    id: 10,
    name: "Anjana Magar",
    image: "https://i.pravatar.cc/150?img=54", 
    occupation: "Project Manager",
    education: "MBA",
  },
  {
    id: 11,
    name: "Suman Basnet",
    image: "https://i.pravatar.cc/150?img=34", 
    occupation: "Cyber Security Analyst",
    education: "B.Sc. CSIT",
  },
  {
    id: 12,
    name: "Manish Shahi",
    image: "https://i.pravatar.cc/150?img=35",
    occupation: "DevOps Engineer",
    education: "B.E. Software",
  },
  {
    id: 13,
    name: "Bhawana Poudel",
    image: "https://i.pravatar.cc/150?img=60", 
    occupation: "System Analyst",
    education: "BIM",
  },
  {
    id: 14,
    name: "Deepak Thapa",
    image: "https://i.pravatar.cc/150?img=41", 
    occupation: "Game Developer",
    education: "B.Sc. CSIT",
  },
  {
    id: 15,
    name: "Sarita Lama",
    image: "https://i.pravatar.cc/150?img=61", 
    occupation: "Database Administrator",
    education: "BCA",
  },
  {
    id: 16,
    name: "Rupesh Adhikari",
    image: "https://i.pravatar.cc/150?img=42", 
    occupation: "Network Engineer",
    education: "B.E. Electronics & Comm.",
  },
  {
    id: 17,
    name: "Sunita Raut",
    image: "https://i.pravatar.cc/150?img=62", 
    occupation: "AI/ML Engineer",
    education: "M.Sc. AI",
  },
  {
    id: 18,
    name: "Rajesh Maharjan",
    image: "https://i.pravatar.cc/150?img=43",
    occupation: "Blockchain Developer",
    education: "B.Sc. CSIT",
  },
  {
    id: 19,
    name: "Puja Shrestha",
    image: "https://i.pravatar.cc/150?img=63", 
    occupation: "QA Tester",
    education: "BIM",
  },
  {
    id: 20,
    name: "Kushal Bista",
    image: "https://i.pravatar.cc/150?img=44", 
    occupation: "Full Stack Developer",
    education: "B.E. Software",
  },
];
